# Neo4J Configurations
neo4jConfig:
    dbLocation: C:/temp/graph-db
    enableWebserver: false

activeMQConfig:
    brokerName: fig
    brokerURI: "tcp://localhost:61616"
    dataFolderLocation: "C:/temp/ems_data"
    requestQueue: "fig.RequestQueue"
